import type { Metadata } from "next";
import { LegalLayout } from "@/components/LegalLayout";
import { CONTACT_EMAIL } from "@/lib/config";

export const metadata: Metadata = {
  title: "Terms of Service — VeriSprint",
  description: "The terms governing use of the VeriSprint platform, GitHub App, and public site.",
};

export default function TermsPage() {
  return (
    <LegalLayout eyebrow="Legal" title="Terms of Service" effectiveDate="August 2026">
      <p>
        These terms govern your use of VeriSprint — the web application, the GitHub App, and the API. By creating
        a workspace, installing the GitHub App, or using a Client Portal link, you agree to them.
      </p>

      <h2>1. The service</h2>
      <p>
        VeriSprint connects to GitHub repositories you explicitly authorize, analyzes commit and pull request
        activity, and produces the Evidence Ledger, Confidence Scores, reconciliation flags, and related features
        described on our{" "}
        <a href="/features" className="text-brand underline">Features</a> page. The GitHub App only ever requests
        read-only scopes (Contents, Metadata, Pull Requests) — it cannot push code, merge PRs, or modify repo
        settings.
      </p>

      <h2>2. Accounts and roles</h2>
      <p>
        You&apos;re responsible for the accuracy of the information you provide and for activity under your
        account. Workspace Admins control who has access to their workspace and at what role — Super Admin,
        Workspace Admin, Manager, Developer, or the read-only Client Portal role — and are responsible for
        removing access when it&apos;s no longer needed.
      </p>

      <h2>3. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use VeriSprint to access, analyze, or store code you don&apos;t have the right to connect (e.g. a repository you don&apos;t own or aren&apos;t authorized to grant access to).</li>
        <li>Attempt to bypass workspace isolation, RBAC, or rate limiting, or to access another workspace&apos;s data.</li>
        <li>Use the service to build a directly competing product by systematically extracting its analysis via automated means.</li>
        <li>Share a Client Portal link with anyone the workspace owner hasn&apos;t authorized to receive it.</li>
        <li>Interfere with the service&apos;s availability for other workspaces (e.g. abusive request volume against the API).</li>
      </ul>

      <h2>4. Plans and billing</h2>
      <p>
        The Free tier has no time limit and requires no payment method. Paid tiers are billed per the plan you
        select at{" "}
        <a href="/pricing" className="text-brand underline">Pricing</a>, processed by Stripe. You can downgrade or
        cancel at any time from your workspace settings; downgrades take effect at the end of the current billing
        period, and features gated to a higher tier stop working (without deleting your underlying data) once the
        downgrade applies.
      </p>

      <h2>5. Your data, and what we do with it</h2>
      <p>
        You own the code, tickets, and other content you connect to VeriSprint. We process it only to provide the
        service, as described in our{" "}
        <a href="/privacy" className="text-brand underline">Privacy Policy</a> — including sending diffs to an LLM
        provider for analysis, never to train a model on your code. You can disconnect a repository or delete your
        workspace at any time; see the Privacy Policy for our data-deletion timeline.
      </p>

      <h2>6. AI-generated content</h2>
      <p>
        Confidence Scores, standup drafts, reconciliation flags, and similar outputs are generated by an LLM
        reasoning over your real commit and PR data. They are judgment calls with cited evidence, not guaranteed
        facts — a human should review a flag or a draft before treating it as final, the same way you&apos;d
        review any other automated suggestion. We built the product to surface its reasoning specifically so this
        review is fast, not so it can be skipped.
      </p>

      <h2>7. Availability and changes</h2>
      <p>
        We aim for high availability but don&apos;t guarantee an uptime SLA on Free or self-serve paid tiers — see
        our{" "}
        <a href="/status" className="text-brand underline">Status page</a> for real-time system health. We may
        change or discontinue a feature; where reasonably possible, we&apos;ll give notice for any change that
        removes a capability you&apos;re actively relying on.
      </p>

      <h2>8. Termination</h2>
      <p>
        You can stop using VeriSprint and delete your workspace at any time. We may suspend or terminate access
        for a workspace that violates Section 3 (Acceptable use), with notice where practical, and will make a
        reasonable effort to give you an opportunity to export your data first unless the violation involves
        active harm to the service or other users.
      </p>

      <h2>9. Disclaimers and liability</h2>
      <p>
        VeriSprint is provided on an early-access, &ldquo;as-is&rdquo; basis — see the notice at the top of this
        page. We don&apos;t warrant that every judgment the system makes will be accurate; the whole design of the
        Evidence Ledger is to make that judgment inspectable and contestable, not infallible. To the extent
        permitted by law, our liability for any claim arising from your use of the service is limited to the
        amount you paid us in the 12 months before the claim.
      </p>

      <h2>10. Changes to these terms</h2>
      <p>
        If we make a material change, we&apos;ll update the effective date above and, for active workspace users,
        note it in-app before the change takes effect.
      </p>

      <h2>11. Contact</h2>
      <p>
        Questions about these terms:{" "}
        <a href={`mailto:${CONTACT_EMAIL}`} className="text-brand underline">
          {CONTACT_EMAIL}
        </a>
        .
      </p>
    </LegalLayout>
  );
}
