"""add workspace trial_ends_at

Revision ID: 38890830311f
Revises: 5fd8168eef20
Create Date: 2026-08-21 01:51:23.918778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '38890830311f'
down_revision: Union[str, None] = '5fd8168eef20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Data backfill, not just schema: every workspace that predates this
    # migration is on FREE tier with no trial_ends_at — under the new
    # app.billing_access.workspace_has_active_access check, that combination
    # reads as "trial never started" (access denied), which would instantly
    # lock out every existing free workspace the moment this deploys,
    # including ones that have been using the product for a while. Grant
    # them a fresh trial window starting now, not backdated to their real
    # created_at — the point is a graceful transition into the new system,
    # not a surprise retroactive expiry.
    op.execute(
        "UPDATE workspaces SET trial_ends_at = now() + interval '2 days' "
        "WHERE plan_tier = 'FREE' AND trial_ends_at IS NULL"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'trial_ends_at')
    # ### end Alembic commands ###
