"""phase 2 team goals, integrations, blocker flag

Revision ID: 3dd2a630d2ad
Revises: 601673efb4f8
Create Date: 2026-08-16 11:41:48.802660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3dd2a630d2ad'
down_revision: Union[str, None] = '601673efb4f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerate doesn't detect new *values* added to an existing Postgres
    # enum type (only new/dropped types) — added by hand, same pattern as the
    # v2 Phase 2/3 migration.
    op.execute("ALTER TYPE reconciliationflagtype ADD VALUE IF NOT EXISTS 'POSSIBLE_BLOCKER'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'ERROR', name='integrationstatus'), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'provider')
    )
    op.create_index(op.f('ix_integrations_workspace_id'), 'integrations', ['workspace_id'], unique=False)
    op.create_table('team_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('metric_key', sa.String(length=64), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_goals_repo_id'), 'team_goals', ['repo_id'], unique=False)
    op.create_index(op.f('ix_team_goals_workspace_id'), 'team_goals', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_goals_workspace_id'), table_name='team_goals')
    op.drop_index(op.f('ix_team_goals_repo_id'), table_name='team_goals')
    op.drop_table('team_goals')
    op.drop_index(op.f('ix_integrations_workspace_id'), table_name='integrations')
    op.drop_table('integrations')
    # ### end Alembic commands ###
