"""add pricing_plans table and multi-provider subscription fields

Revision ID: 5fd8168eef20
Revises: 69715dc3931a
Create Date: 2026-08-20 18:27:51.792536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '5fd8168eef20'
down_revision: Union[str, None] = '69715dc3931a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # create_type=False — the `workspaceplantier` Postgres enum type already
    # exists (created by an earlier migration for Workspace.plan_tier);
    # autogenerate doesn't know that when a *new* table is the first thing
    # in this migration to reference it, and emits a CREATE TYPE that
    # collides with the existing one otherwise.
    op.create_table('pricing_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tier', postgresql.ENUM('FREE', 'TEAM', 'GROWTH', 'AGENCY', 'ENTERPRISE', name='workspaceplantier', create_type=False), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('price_usd', sa.Float(), nullable=False),
    sa.Column('billing_interval', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('paystack_plan_code', sa.String(length=255), nullable=True),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_plans_tier'), 'pricing_plans', ['tier'], unique=True)
    # server_default is required here, not just a Python-level default —
    # `subscriptions` already has real rows (every existing workspace's
    # Subscription), and NOT NULL with no default would fail against them.
    op.add_column('subscriptions', sa.Column('payment_provider', sa.String(length=20), nullable=False, server_default='stripe'))
    op.add_column('subscriptions', sa.Column('paystack_customer_code', sa.String(length=255), nullable=True))
    op.add_column('subscriptions', sa.Column('paystack_subscription_code', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_subscriptions_paystack_customer_code'), 'subscriptions', ['paystack_customer_code'], unique=False)
    op.create_index(op.f('ix_subscriptions_paystack_subscription_code'), 'subscriptions', ['paystack_subscription_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_paystack_subscription_code'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_paystack_customer_code'), table_name='subscriptions')
    op.drop_column('subscriptions', 'paystack_subscription_code')
    op.drop_column('subscriptions', 'paystack_customer_code')
    op.drop_column('subscriptions', 'payment_provider')
    op.drop_index(op.f('ix_pricing_plans_tier'), table_name='pricing_plans')
    op.drop_table('pricing_plans')
    # ### end Alembic commands ###
