"""v3 workspace multi-tenancy and auth

Revision ID: 601673efb4f8
Revises: cb93aae0f6d5
Create Date: 2026-08-16 07:50:46.522952

Hand-adjusted from the autogenerated version: `installations` -> `workspaces`
and `repos.installation_id` -> `repos.workspace_id` are done as renames (not
drop+recreate), and the `workspace_settings` singleton row's values are
copied onto the workspace before the table is dropped — autogenerate would
have silently destroyed all three, and the added-NOT-NULL-column step on
`repos` would have failed outright against existing rows.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '601673efb4f8'
down_revision: Union[str, None] = 'cb93aae0f6d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create every new enum type explicitly up front — `op.add_column()` with
    # a bare `sa.Enum(...)` does NOT auto-emit CREATE TYPE the way
    # `create_table()` does, so every enum referenced below is declared with
    # `create_type=False` and must already exist by the time it's used.
    op.execute("CREATE TYPE workspaceplantier AS ENUM ('FREE', 'TEAM', 'GROWTH', 'AGENCY', 'ENTERPRISE')")
    op.execute("CREATE TYPE workspacestatus AS ENUM ('ACTIVE', 'SUSPENDED', 'CANCELED')")
    op.execute("CREATE TYPE errorseverity AS ENUM ('INFO', 'WARNING', 'ERROR', 'CRITICAL')")
    op.execute("CREATE TYPE subscriptionstatus AS ENUM ('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED')")

    # ### new operator/billing tables (autogenerated, unchanged) ###
    op.create_table('feature_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('enabled_globally', sa.Boolean(), nullable=False),
    sa.Column('enabled_workspace_ids', sa.JSON(), nullable=False),
    sa.Column('min_plan_tier', postgresql.ENUM('FREE', 'TEAM', 'GROWTH', 'AGENCY', 'ENTERPRISE', name='workspaceplantier', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_flags_key'), 'feature_flags', ['key'], unique=True)

    # ### installations -> workspaces: RENAME, then extend (preserves repos.installation_id's FK target and all existing rows) ###
    op.rename_table('installations', 'workspaces')
    op.add_column('workspaces', sa.Column('name', sa.String(length=255), nullable=True))
    op.execute("UPDATE workspaces SET name = account_login WHERE name IS NULL")
    op.alter_column('workspaces', 'name', nullable=False)
    op.add_column('workspaces', sa.Column(
        'plan_tier', postgresql.ENUM('FREE', 'TEAM', 'GROWTH', 'AGENCY', 'ENTERPRISE', name='workspaceplantier', create_type=False),
        nullable=False, server_default='FREE',
    ))
    op.add_column('workspaces', sa.Column(
        'status', postgresql.ENUM('ACTIVE', 'SUSPENDED', 'CANCELED', name='workspacestatus', create_type=False),
        nullable=False, server_default='ACTIVE',
    ))
    op.add_column('workspaces', sa.Column('mrr', sa.Float(), nullable=False, server_default='0'))
    op.add_column('workspaces', sa.Column('logo_url', sa.String(length=1024), nullable=True))
    op.add_column('workspaces', sa.Column('primary_color_hex', sa.String(length=7), nullable=False, server_default='#111827'))
    op.add_column('workspaces', sa.Column('avg_standup_minutes', sa.Integer(), nullable=False, server_default='15'))
    op.add_column('workspaces', sa.Column('hourly_rate_usd', sa.Float(), nullable=True))
    op.add_column('workspaces', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # Drop the server defaults added only to satisfy the NOT NULL backfill above —
    # the ORM model supplies these as Python-side defaults on insert, not server-side.
    op.alter_column('workspaces', 'plan_tier', server_default=None)
    op.alter_column('workspaces', 'status', server_default=None)
    op.alter_column('workspaces', 'mrr', server_default=None)
    op.alter_column('workspaces', 'primary_color_hex', server_default=None)
    op.alter_column('workspaces', 'avg_standup_minutes', server_default=None)
    op.execute("ALTER INDEX ix_installations_github_installation_id RENAME TO ix_workspaces_github_installation_id")

    # Carry the (single, in practice) workspace_settings row's branding/ROI
    # config onto the now-per-tenant workspaces table before dropping it.
    op.execute("""
        UPDATE workspaces w
        SET logo_url = ws.logo_url,
            primary_color_hex = ws.primary_color_hex,
            avg_standup_minutes = ws.avg_standup_minutes,
            hourly_rate_usd = ws.hourly_rate_usd
        FROM workspace_settings ws
        WHERE NOT EXISTS (SELECT 1 FROM workspace_settings HAVING count(*) > 1)
    """)
    op.drop_table('workspace_settings')

    # ### remaining new operator tables (reference workspaces, must come after the rename above) ###
    op.create_table('error_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('severity', postgresql.ENUM('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='errorseverity', create_type=False), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('stack_ref', sa.String(length=255), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_error_events_created_at'), 'error_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_error_events_severity'), 'error_events', ['severity'], unique=False)
    op.create_index(op.f('ix_error_events_source'), 'error_events', ['source'], unique=False)
    op.create_index(op.f('ix_error_events_workspace_id'), 'error_events', ['workspace_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('plan_tier', postgresql.ENUM('FREE', 'TEAM', 'GROWTH', 'AGENCY', 'ENTERPRISE', name='workspaceplantier', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELED', name='subscriptionstatus', create_type=False), nullable=False),
    sa.Column('mrr', sa.Float(), nullable=False),
    sa.Column('renewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('payment_provider_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_stripe_customer_id'), 'subscriptions', ['stripe_customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_workspace_id'), 'subscriptions', ['workspace_id'], unique=True)
    op.create_table('system_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_metrics_metric_name'), 'system_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_system_metrics_recorded_at'), 'system_metrics', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_system_metrics_workspace_id'), 'system_metrics', ['workspace_id'], unique=False)
    op.create_table('client_portal_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['report_documents.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_portal_links_report_id'), 'client_portal_links', ['report_id'], unique=False)
    op.create_index(op.f('ix_client_portal_links_token'), 'client_portal_links', ['token'], unique=True)
    op.create_index(op.f('ix_client_portal_links_workspace_id'), 'client_portal_links', ['workspace_id'], unique=False)

    # ### audit_log_entries: additive nullable columns ###
    op.add_column('audit_log_entries', sa.Column('actor_user_id', sa.UUID(), nullable=True))
    op.add_column('audit_log_entries', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_audit_log_entries_actor_user_id'), 'audit_log_entries', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_workspace_id'), 'audit_log_entries', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'audit_log_entries', 'users', ['actor_user_id'], ['id'])
    op.create_foreign_key(None, 'audit_log_entries', 'workspaces', ['workspace_id'], ['id'])

    # ### repos.installation_id -> repos.workspace_id: RENAME (preserves the existing FK values, no NOT NULL backfill needed) ###
    op.alter_column('repos', 'installation_id', new_column_name='workspace_id')
    op.drop_constraint(op.f('repos_installation_id_github_repo_id_key'), 'repos', type_='unique')
    op.create_unique_constraint(None, 'repos', ['workspace_id', 'github_repo_id'])
    op.drop_constraint(op.f('repos_installation_id_fkey'), 'repos', type_='foreignkey')
    op.create_foreign_key(None, 'repos', 'workspaces', ['workspace_id'], ['id'])
    op.create_index(op.f('ix_repos_workspace_id'), 'repos', ['workspace_id'], unique=False)

    # ### users: auth fields (0 existing rows at migration time — plain additive/type changes) ###
    op.add_column('users', sa.Column('workspace_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('users', 'token_version', server_default=None)
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'github_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'github_login',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT")
    op.execute("""
        ALTER TABLE users ALTER COLUMN role TYPE VARCHAR(32) USING role::text
    """)
    op.execute("CREATE TYPE userrole AS ENUM ('SUPER_ADMIN', 'WORKSPACE_ADMIN', 'MANAGER', 'DEVELOPER', 'CLIENT')")
    op.execute("""
        ALTER TABLE users ALTER COLUMN role TYPE userrole USING upper(role)::userrole
    """)
    op.alter_column('users', 'role', server_default='DEVELOPER')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_workspace_id'), 'users', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'users', 'workspaces', ['workspace_id'], ['id'])


def downgrade() -> None:
    op.drop_constraint('users_workspace_id_fkey', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_workspace_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE VARCHAR(32) USING lower(role::text)")
    op.execute("DROP TYPE userrole")
    op.alter_column('users', 'role', server_default='developer')
    op.alter_column('users', 'github_login',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'github_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'token_version')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'workspace_id')

    op.drop_index(op.f('ix_repos_workspace_id'), table_name='repos')
    op.drop_constraint('repos_workspace_id_fkey', 'repos', type_='foreignkey')
    op.drop_constraint('repos_workspace_id_github_repo_id_key', 'repos', type_='unique')
    op.create_foreign_key(op.f('repos_installation_id_fkey'), 'repos', 'workspaces', ['workspace_id'], ['id'])
    op.alter_column('repos', 'workspace_id', new_column_name='installation_id')
    op.create_unique_constraint(op.f('repos_installation_id_github_repo_id_key'), 'repos', ['installation_id', 'github_repo_id'])

    op.drop_constraint('audit_log_entries_workspace_id_fkey', 'audit_log_entries', type_='foreignkey')
    op.drop_constraint('audit_log_entries_actor_user_id_fkey', 'audit_log_entries', type_='foreignkey')
    op.drop_index(op.f('ix_audit_log_entries_workspace_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_actor_user_id'), table_name='audit_log_entries')
    op.drop_column('audit_log_entries', 'workspace_id')
    op.drop_column('audit_log_entries', 'actor_user_id')

    op.drop_index(op.f('ix_client_portal_links_workspace_id'), table_name='client_portal_links')
    op.drop_index(op.f('ix_client_portal_links_token'), table_name='client_portal_links')
    op.drop_index(op.f('ix_client_portal_links_report_id'), table_name='client_portal_links')
    op.drop_table('client_portal_links')
    op.drop_index(op.f('ix_system_metrics_workspace_id'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_recorded_at'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_metric_name'), table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_subscriptions_workspace_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_stripe_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_error_events_workspace_id'), table_name='error_events')
    op.drop_index(op.f('ix_error_events_source'), table_name='error_events')
    op.drop_index(op.f('ix_error_events_severity'), table_name='error_events')
    op.drop_index(op.f('ix_error_events_created_at'), table_name='error_events')
    op.drop_table('error_events')

    op.create_table('workspace_settings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logo_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('primary_color_hex', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('avg_standup_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hourly_rate_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_settings_pkey'))
    )

    op.execute("ALTER INDEX ix_workspaces_github_installation_id RENAME TO ix_installations_github_installation_id")
    op.drop_column('workspaces', 'updated_at')
    op.drop_column('workspaces', 'hourly_rate_usd')
    op.drop_column('workspaces', 'avg_standup_minutes')
    op.drop_column('workspaces', 'primary_color_hex')
    op.drop_column('workspaces', 'logo_url')
    op.drop_column('workspaces', 'mrr')
    op.drop_column('workspaces', 'status')
    op.drop_column('workspaces', 'plan_tier')
    op.drop_column('workspaces', 'name')
    op.rename_table('workspaces', 'installations')

    op.drop_index(op.f('ix_feature_flags_key'), table_name='feature_flags')
    op.drop_table('feature_flags')

    op.execute("DROP TYPE subscriptionstatus")
    op.execute("DROP TYPE errorseverity")
    op.execute("DROP TYPE workspacestatus")
    op.execute("DROP TYPE workspaceplantier")
