"""init schema

Revision ID: 64d443b2cc0a
Revises: 
Create Date: 2026-08-15 15:05:52.677172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision: str = '64d443b2cc0a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Required for the EvidenceItem.embedding column (Repo Chat retrieval).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_id', sa.Integer(), nullable=False),
    sa.Column('github_login', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('slack_user_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_github_login'), 'users', ['github_login'], unique=False)
    op.create_table('installations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('github_installation_id', sa.Integer(), nullable=False),
    sa.Column('account_login', sa.String(length=255), nullable=False),
    sa.Column('installed_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installations_github_installation_id'), 'installations', ['github_installation_id'], unique=True)
    op.create_table('repos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.UUID(), nullable=False),
    sa.Column('github_repo_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=512), nullable=False),
    sa.Column('default_branch', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id', 'github_repo_id')
    )
    op.create_index(op.f('ix_repos_github_repo_id'), 'repos', ['github_repo_id'], unique=False)
    op.create_table('pull_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('author_github_login', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('merged_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('linked_ticket_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'number')
    )
    op.create_index(op.f('ix_pull_requests_linked_ticket_key'), 'pull_requests', ['linked_ticket_key'], unique=False)
    op.create_index(op.f('ix_pull_requests_repo_id'), 'pull_requests', ['repo_id'], unique=False)
    op.create_table('standup_updates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('author_github_login', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('commit_ids', sa.JSON(), nullable=False),
    sa.Column('posted_to_slack', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_github_login', 'repo_id', 'date')
    )
    op.create_index('ix_standup_repo_date', 'standup_updates', ['repo_id', 'date'], unique=False)
    op.create_index(op.f('ix_standup_updates_author_github_login'), 'standup_updates', ['author_github_login'], unique=False)
    op.create_index(op.f('ix_standup_updates_repo_id'), 'standup_updates', ['repo_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('assignee_github_login', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'key')
    )
    op.create_index(op.f('ix_tickets_key'), 'tickets', ['key'], unique=False)
    op.create_index(op.f('ix_tickets_repo_id'), 'tickets', ['repo_id'], unique=False)
    op.create_table('commits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('pull_request_id', sa.UUID(), nullable=True),
    sa.Column('sha', sa.String(length=40), nullable=False),
    sa.Column('author_github_login', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('committed_at', sa.DateTime(), nullable=False),
    sa.Column('raw_diff_object_key', sa.String(length=1024), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('deletions', sa.Integer(), nullable=False),
    sa.Column('linked_ticket_key', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pull_request_id'], ['pull_requests.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'sha')
    )
    op.create_index(op.f('ix_commits_author_github_login'), 'commits', ['author_github_login'], unique=False)
    op.create_index(op.f('ix_commits_linked_ticket_key'), 'commits', ['linked_ticket_key'], unique=False)
    op.create_index(op.f('ix_commits_repo_id'), 'commits', ['repo_id'], unique=False)
    op.create_index(op.f('ix_commits_sha'), 'commits', ['sha'], unique=False)
    op.create_table('confidence_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_item_ids', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confidence_scores_ticket_id'), 'confidence_scores', ['ticket_id'], unique=False)
    op.create_table('reconciliation_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('flag_type', sa.Enum('CLAIMED_NOT_SHIPPED', 'SHIPPED_NOT_CLAIMED', 'LOW_CONFIDENCE', name='reconciliationflagtype'), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_flags_ticket_id'), 'reconciliation_flags', ['ticket_id'], unique=False)
    op.create_table('evidence_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commit_id', sa.UUID(), nullable=False),
    sa.Column('ticket_key', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.Enum('SUMMARY', 'TEST_ADDED', 'TEST_MISSING', 'TODO_FOUND', 'DEAD_CODE', 'CALL_GRAPH_CHANGE', 'RISK', name='evidencekind'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('line_range', sa.String(length=32), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['commit_id'], ['commits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_items_commit_id'), 'evidence_items', ['commit_id'], unique=False)
    op.create_index(op.f('ix_evidence_items_ticket_key'), 'evidence_items', ['ticket_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_items_ticket_key'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_commit_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_reconciliation_flags_ticket_id'), table_name='reconciliation_flags')
    op.drop_table('reconciliation_flags')
    op.drop_index(op.f('ix_confidence_scores_ticket_id'), table_name='confidence_scores')
    op.drop_table('confidence_scores')
    op.drop_index(op.f('ix_commits_sha'), table_name='commits')
    op.drop_index(op.f('ix_commits_repo_id'), table_name='commits')
    op.drop_index(op.f('ix_commits_linked_ticket_key'), table_name='commits')
    op.drop_index(op.f('ix_commits_author_github_login'), table_name='commits')
    op.drop_table('commits')
    op.drop_index(op.f('ix_tickets_repo_id'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_key'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_standup_updates_repo_id'), table_name='standup_updates')
    op.drop_index(op.f('ix_standup_updates_author_github_login'), table_name='standup_updates')
    op.drop_index('ix_standup_repo_date', table_name='standup_updates')
    op.drop_table('standup_updates')
    op.drop_index(op.f('ix_pull_requests_repo_id'), table_name='pull_requests')
    op.drop_index(op.f('ix_pull_requests_linked_ticket_key'), table_name='pull_requests')
    op.drop_table('pull_requests')
    op.drop_index(op.f('ix_repos_github_repo_id'), table_name='repos')
    op.drop_table('repos')
    op.drop_index(op.f('ix_installations_github_installation_id'), table_name='installations')
    op.drop_table('installations')
    op.drop_index(op.f('ix_users_github_login'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
