"""repo slack channel

Revision ID: 6522289028d3
Revises: e8d4fffb7ac5
Create Date: 2026-08-15 16:00:19.561838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6522289028d3'
down_revision: Union[str, None] = 'e8d4fffb7ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('slack_channel_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'slack_channel_id')
    # ### end Alembic commands ###
