"""add report builder custom sections

Revision ID: 69715dc3931a
Revises: 7e933e5df282
Create Date: 2026-08-20 13:37:35.756959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '69715dc3931a'
down_revision: Union[str, None] = '7e933e5df282'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_documents', sa.Column('custom_sections', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

    # Not autogenerated: Alembic's autogenerate doesn't diff native Postgres
    # enum value additions. The `reporttype` enum stores each ReportType
    # member's *name* (e.g. 'CLIENT_PORTAL'), not its lowercase `.value`, so
    # the new ReportType.CUSTOM member needs its literal name added here or
    # every custom-report insert 500s. `ADD VALUE` can't run inside the
    # transaction Alembic wraps migrations in by default (pre-commit use is
    # disallowed by Postgres), hence the autocommit block.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE reporttype ADD VALUE IF NOT EXISTS 'CUSTOM'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_documents', 'custom_sections')
    # ### end Alembic commands ###
    # Postgres has no `ALTER TYPE ... DROP VALUE` — the 'CUSTOM' enum label
    # intentionally stays behind on downgrade, same as any other Postgres
    # enum-value migration; harmless if unused.
