"""add ai_tool_subscriptions table

Revision ID: 7e933e5df282
Revises: e502897d9293
Create Date: 2026-08-20 13:18:55.891922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e933e5df282'
down_revision: Union[str, None] = 'e502897d9293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_tool_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=120), nullable=False),
    sa.Column('seat_count', sa.Integer(), nullable=False),
    sa.Column('cost_per_seat_usd', sa.Float(), nullable=False),
    sa.Column('billing_period', sa.String(length=16), nullable=False),
    sa.Column('started_on', sa.Date(), nullable=False),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_tool_subscriptions_workspace_id'), 'ai_tool_subscriptions', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_tool_subscriptions_workspace_id'), table_name='ai_tool_subscriptions')
    op.drop_table('ai_tool_subscriptions')
    # ### end Alembic commands ###
