"""add workspace mcp_token

Revision ID: e502897d9293
Revises: edd3e6f7a3b5
Create Date: 2026-08-20 13:03:01.551632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e502897d9293'
down_revision: Union[str, None] = 'edd3e6f7a3b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('mcp_token', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_workspaces_mcp_token'), 'workspaces', ['mcp_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workspaces_mcp_token'), table_name='workspaces')
    op.drop_column('workspaces', 'mcp_token')
    # ### end Alembic commands ###
