"""phase 2/3 features

Revision ID: e8d4fffb7ac5
Revises: 64d443b2cc0a
Create Date: 2026-08-15 15:42:19.863083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e8d4fffb7ac5'
down_revision: Union[str, None] = '64d443b2cc0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Autogenerate doesn't detect new values on an existing native Postgres
    # enum type — add the three new ReconciliationFlagType members by hand.
    op.execute("ALTER TYPE reconciliationflagtype ADD VALUE IF NOT EXISTS 'TICKET_DRIFT'")
    op.execute("ALTER TYPE reconciliationflagtype ADD VALUE IF NOT EXISTS 'ORPHAN_COMMIT'")
    op.execute("ALTER TYPE reconciliationflagtype ADD VALUE IF NOT EXISTS 'ANOMALY_ACTIVITY_DROP'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('primary_color_hex', sa.String(length=7), nullable=False),
    sa.Column('avg_standup_minutes', sa.Integer(), nullable=False),
    sa.Column('hourly_rate_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entries_action'), 'audit_log_entries', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_created_at'), 'audit_log_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_entries_repo_id'), 'audit_log_entries', ['repo_id'], unique=False)
    op.create_table('chat_queries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('asked_by', sa.String(length=255), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('cited_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_queries_created_at'), 'chat_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_queries_repo_id'), 'chat_queries', ['repo_id'], unique=False)
    op.create_table('report_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.Enum('CLIENT_PORTAL', 'INVESTOR_UPDATE', 'SPRINT_ROLLUP', 'ONBOARDING_DOC', name='reporttype'), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_documents_repo_id'), 'report_documents', ['repo_id'], unique=False)
    op.create_index(op.f('ix_report_documents_report_type'), 'report_documents', ['report_type'], unique=False)
    op.create_index(op.f('ix_report_documents_share_token'), 'report_documents', ['share_token'], unique=True)
    op.create_table('sprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('planned_ticket_keys', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'name')
    )
    op.create_index(op.f('ix_sprints_repo_id'), 'sprints', ['repo_id'], unique=False)
    op.add_column('reconciliation_flags', sa.Column('repo_id', sa.UUID(), nullable=True))
    op.add_column('reconciliation_flags', sa.Column('person_github_login', sa.String(length=255), nullable=True))
    op.add_column('reconciliation_flags', sa.Column('commit_id', sa.UUID(), nullable=True))
    op.add_column(
        'reconciliation_flags',
        sa.Column('detail_json', sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
    )
    op.alter_column('reconciliation_flags', 'detail_json', server_default=None)
    op.alter_column('reconciliation_flags', 'ticket_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_reconciliation_flags_person_github_login'), 'reconciliation_flags', ['person_github_login'], unique=False)
    op.create_index(op.f('ix_reconciliation_flags_repo_id'), 'reconciliation_flags', ['repo_id'], unique=False)
    op.create_foreign_key(None, 'reconciliation_flags', 'commits', ['commit_id'], ['id'])
    op.create_foreign_key(None, 'reconciliation_flags', 'repos', ['repo_id'], ['id'])
    op.add_column('tickets', sa.Column('acceptance_criteria', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('sso_subject', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('sso_provider', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_sso_subject'), 'users', ['sso_subject'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # Note: the TICKET_DRIFT/ORPHAN_COMMIT/ANOMALY_ACTIVITY_DROP enum values
    # added in upgrade() are NOT removed here — Postgres has no ALTER TYPE ...
    # DROP VALUE; removing them requires recreating the type, which is not
    # safe to do blindly against a table that may already reference them.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sso_subject'), table_name='users')
    op.drop_column('users', 'sso_provider')
    op.drop_column('users', 'sso_subject')
    op.drop_column('tickets', 'acceptance_criteria')
    op.drop_constraint(None, 'reconciliation_flags', type_='foreignkey')
    op.drop_constraint(None, 'reconciliation_flags', type_='foreignkey')
    op.drop_index(op.f('ix_reconciliation_flags_repo_id'), table_name='reconciliation_flags')
    op.drop_index(op.f('ix_reconciliation_flags_person_github_login'), table_name='reconciliation_flags')
    op.alter_column('reconciliation_flags', 'ticket_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('reconciliation_flags', 'detail_json')
    op.drop_column('reconciliation_flags', 'commit_id')
    op.drop_column('reconciliation_flags', 'person_github_login')
    op.drop_column('reconciliation_flags', 'repo_id')
    op.drop_index(op.f('ix_sprints_repo_id'), table_name='sprints')
    op.drop_table('sprints')
    op.drop_index(op.f('ix_report_documents_share_token'), table_name='report_documents')
    op.drop_index(op.f('ix_report_documents_report_type'), table_name='report_documents')
    op.drop_index(op.f('ix_report_documents_repo_id'), table_name='report_documents')
    op.drop_table('report_documents')
    op.drop_index(op.f('ix_chat_queries_repo_id'), table_name='chat_queries')
    op.drop_index(op.f('ix_chat_queries_created_at'), table_name='chat_queries')
    op.drop_table('chat_queries')
    op.drop_index(op.f('ix_audit_log_entries_repo_id'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_created_at'), table_name='audit_log_entries')
    op.drop_index(op.f('ix_audit_log_entries_action'), table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    op.drop_table('workspace_settings')
    # ### end Alembic commands ###
