"""phase 3 value stream, pulse surveys, working agreements, workspace sso

Revision ID: f152b741c790
Revises: 3dd2a630d2ad
Create Date: 2026-08-16 12:39:18.870761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f152b741c790'
down_revision: Union[str, None] = '3dd2a630d2ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_sso_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('issuer', sa.String(length=512), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('scim_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_sso_configs_scim_token'), 'workspace_sso_configs', ['scim_token'], unique=True)
    op.create_index(op.f('ix_workspace_sso_configs_workspace_id'), 'workspace_sso_configs', ['workspace_id'], unique=True)
    op.create_table('pulse_surveys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pulse_surveys_workspace_id'), 'pulse_surveys', ['workspace_id'], unique=False)
    op.create_table('working_agreements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('updated_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_working_agreements_repo_id'), 'working_agreements', ['repo_id'], unique=False)
    op.create_index(op.f('ix_working_agreements_workspace_id'), 'working_agreements', ['workspace_id'], unique=False)
    op.create_table('pulse_survey_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['pulse_surveys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_id', 'user_id')
    )
    op.create_index(op.f('ix_pulse_survey_responses_survey_id'), 'pulse_survey_responses', ['survey_id'], unique=False)
    op.create_index(op.f('ix_pulse_survey_responses_user_id'), 'pulse_survey_responses', ['user_id'], unique=False)
    op.create_table('ticket_status_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.String(length=64), nullable=False),
    sa.Column('to_status', sa.String(length=64), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_status_changes_changed_at'), 'ticket_status_changes', ['changed_at'], unique=False)
    op.create_index(op.f('ix_ticket_status_changes_ticket_id'), 'ticket_status_changes', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_status_changes_ticket_id'), table_name='ticket_status_changes')
    op.drop_index(op.f('ix_ticket_status_changes_changed_at'), table_name='ticket_status_changes')
    op.drop_table('ticket_status_changes')
    op.drop_index(op.f('ix_pulse_survey_responses_user_id'), table_name='pulse_survey_responses')
    op.drop_index(op.f('ix_pulse_survey_responses_survey_id'), table_name='pulse_survey_responses')
    op.drop_table('pulse_survey_responses')
    op.drop_index(op.f('ix_working_agreements_workspace_id'), table_name='working_agreements')
    op.drop_index(op.f('ix_working_agreements_repo_id'), table_name='working_agreements')
    op.drop_table('working_agreements')
    op.drop_index(op.f('ix_pulse_surveys_workspace_id'), table_name='pulse_surveys')
    op.drop_table('pulse_surveys')
    op.drop_index(op.f('ix_workspace_sso_configs_workspace_id'), table_name='workspace_sso_configs')
    op.drop_index(op.f('ix_workspace_sso_configs_scim_token'), table_name='workspace_sso_configs')
    op.drop_table('workspace_sso_configs')
    # ### end Alembic commands ###
